# Generated by Django 3.1.1 on 2021-02-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nome', models.CharField(max_length=150)),
                ('pastor', models.CharField(max_length=150)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('texto', models.TextField()),
                ('local', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Novidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nome', models.CharField(max_length=150)),
                ('texto', models.TextField()),
            ],
        ),
    ]
