# Generated by Django 3.1.6 on 2021-02-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultos',
            options={'verbose_name': 'Culto', 'verbose_name_plural': 'Cultos'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='novidades',
            options={'verbose_name': 'Novidade', 'verbose_name_plural': 'Novidades'},
        ),
        migrations.AddField(
            model_name='cultos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cultos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='novidades',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='novidades',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultos',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
