# Generated by Django 3.1.1 on 2021-02-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20210215_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultos',
            old_name='nome',
            new_name='tema',
        ),
        migrations.AddField(
            model_name='cultos',
            name='descricao',
            field=models.TextField(default='dddd'),
            preserve_default=False,
        ),
    ]
