# Generated by Django 3.1.1 on 2021-02-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_novidades_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultos',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateField(),
        ),
    ]
