# Generated by Django 3.1.1 on 2021-02-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20210224_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultos',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
