# Generated by Django 3.1.1 on 2021-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20210225_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cultos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='eventos'),
        ),
        migrations.AlterField(
            model_name='novidades',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='novidades'),
        ),
    ]
