# Generated by Django 3.1.1 on 2020-09-18 01:07

import registros.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to=registros.models.get_file_path, verbose_name='Imagem')),
                ('nome_completo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('J', 'Jovem'), ('P', 'Pastor'), ('L', 'Lider')], default='J', max_length=6)),
                ('identificacao_igreja', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(default=None, max_length=100, unique=True)),
                ('aniversario', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Registro Pessoal',
                'verbose_name_plural': 'Registros Pessoais',
            },
        ),
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=150, unique=True)),
                ('file', models.FileField(upload_to='Registros')),
                ('descreva_atividade', models.TextField()),
                ('Data', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('igreja_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja')),
            ],
        ),
    ]
