# Generated by Django 3.1.1 on 2020-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroatividade',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Registros'),
        ),
    ]
