# Generated by Django 3.1.1 on 2020-09-18 09:29

import registros.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20200918_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropessoal',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=registros.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
