# Generated by Django 3.1.1 on 2020-09-18 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jovens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('funcao_na_igreja', models.TextField(help_text='Descreva algo sobre voce')),
            ],
            options={
                'verbose_name': 'Jovem',
                'verbose_name_plural': 'Jovens',
            },
        ),
        migrations.CreateModel(
            name='Novatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('celular_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.celula')),
                ('igreja_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja')),
            ],
            options={
                'verbose_name': 'Novato',
                'verbose_name_plural': 'Novatos',
            },
        ),
    ]
