# Generated by Django 3.1.6 on 2021-02-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerio', models.CharField(choices=[('Musica', 'Musica'), ('Oracao', 'Oracao'), ('Integracao', 'Integracao')], max_length=100)),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
            },
        ),
        migrations.CreateModel(
            name='Novatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descreva', models.TextField(help_text='Descreva algo sobre voce')),
            ],
            options={
                'verbose_name': 'Novato',
                'verbose_name_plural': 'Novatos',
            },
        ),
        migrations.CreateModel(
            name='Jovens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igreja.celula')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja')),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.ministerio')),
            ],
            options={
                'verbose_name': 'Jovem',
                'verbose_name_plural': 'Jovens',
            },
        ),
    ]
