# Generated by Django 3.1.1 on 2020-09-18 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0001_initial'),
        ('membros', '0001_initial'),
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jovens',
            name='RegistreSeusDados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registros.registropessoal'),
        ),
        migrations.AddField(
            model_name='jovens',
            name='celula_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JovensDaCelula', to='igreja.celula'),
        ),
        migrations.AddField(
            model_name='jovens',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja'),
        ),
    ]
