# Generated by Django 3.1.1 on 2020-09-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        ('membros', '0002_auto_20200917_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jovens',
            name='RegistreSeusDados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.registropessoal'),
        ),
    ]
