# Generated by Django 3.1.1 on 2021-03-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_auto_20210215_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novatos',
        ),
        migrations.AddField(
            model_name='jovens',
            name='contato',
            field=models.CharField(default='22', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jovens',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='ministerio',
            field=models.CharField(choices=[('Musica', 'Musica'), ('Oracao', 'Oracao'), ('Integracao', 'Integracao'), ('Integracao', 'Integracao')], max_length=100),
        ),
    ]
