# Generated by Django 3.1.1 on 2021-03-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0007_ministerio'),
        ('membros', '0003_auto_20210302_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jovens',
            name='ministerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.ministerio'),
        ),
        migrations.DeleteModel(
            name='Ministerio',
        ),
    ]
