# Generated by Django 3.1.1 on 2021-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_auto_20210305_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jovens',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros'),
        ),
    ]
