# Generated by Django 3.1.1 on 2020-09-18 01:00

import apps.igreja.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('nome_igreja', models.CharField(max_length=200)),
                ('pastor_nome', models.CharField(max_length=150)),
                ('descreva_igreja', models.TextField(help_text='fale um pouco sobre a igreja')),
            ],
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to=apps.igreja.models.get_file_path, verbose_name='Imagem')),
                ('nome', models.CharField(max_length=150)),
                ('id_igreja', models.CharField(max_length=150)),
                ('igreja_pertence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lideres', to='igreja.igreja')),
            ],
            options={
                'verbose_name': 'Lider',
                'verbose_name_plural': 'Lideres',
            },
        ),
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('nome_celula', models.CharField(max_length=200)),
                ('igreja_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Igreja_nome_mae', to='igreja.igreja')),
                ('lider_celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JovensDaCelula', to='igreja.lideres')),
            ],
            options={
                'verbose_name': 'Celula',
                'verbose_name_plural': 'Celulas',
            },
        ),
    ]
