# Generated by Django 3.1.1 on 2020-10-24 02:27

import apps.igreja.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0002_auto_20200918_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=apps.igreja.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
