# Generated by Django 3.1.1 on 2020-10-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0005_auto_20201027_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celula',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja'),
        ),
        migrations.AlterField(
            model_name='celula',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igreja.lideres'),
        ),
    ]
