# Generated by Django 3.1.1 on 2020-11-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0006_auto_20201027_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lideres',
            name='igreja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja'),
        ),
    ]
