# Generated by Django 3.1.6 on 2021-02-12 19:40

from django.db import migrations, models
import django.db.models.deletion
import igreja.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('pastor', models.CharField(max_length=150)),
                ('descricao', models.TextField(help_text='fale um pouco sobre a igreja')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=igreja.models.get_file_path, verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=igreja.models.get_file_path, verbose_name='Imagem')),
                ('nome', models.CharField(max_length=150)),
                ('codigo_igreja', models.CharField(max_length=150)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja')),
            ],
            options={
                'verbose_name': 'Lider',
                'verbose_name_plural': 'Lideres',
            },
        ),
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igreja.igreja')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igreja.lideres')),
            ],
            options={
                'verbose_name': 'Celula',
                'verbose_name_plural': 'Celulas',
            },
        ),
    ]
