# Generated by Django 3.1.1 on 2020-09-18 08:20

import igreja.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lideres',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=igreja.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
