# Generated by Django 3.1.6 on 2021-02-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igreja',
            options={'verbose_name': 'Igreja', 'verbose_name_plural': 'Igrejas'},
        ),
        migrations.AddField(
            model_name='celula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='celula',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lideres',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lideres',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
