# Generated by Django 3.1.1 on 2021-02-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0002_auto_20210215_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='descricao_pastor',
            field=models.TextField(default='adawdawd', help_text='Um pouco da historia do pastor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='igreja',
            name='descricao',
            field=models.TextField(help_text='Sobre a igreja'),
        ),
    ]
