# Generated by Django 3.1.1 on 2020-10-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0003_igreja_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celula',
            old_name='igreja_mae',
            new_name='igreja',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='lider_celula',
            new_name='lider',
        ),
        migrations.RenameField(
            model_name='celula',
            old_name='nome_celula',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='igreja',
            old_name='descreva_igreja',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='igreja',
            old_name='nome_igreja',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='igreja',
            old_name='pastor_nome',
            new_name='pastor',
        ),
        migrations.RenameField(
            model_name='lideres',
            old_name='id_igreja',
            new_name='codigo_igreja',
        ),
        migrations.RenameField(
            model_name='lideres',
            old_name='igreja_pertence',
            new_name='igreja',
        ),
    ]
