# Generated by Django 3.1.1 on 2021-02-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0003_auto_20210222_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='celula',
            name='contato',
            field=models.CharField(default=3232323, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celula',
            name='descricao',
            field=models.TextField(default='232323'),
            preserve_default=False,
        ),
    ]
