# Generated by Django 3.1.1 on 2020-10-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0004_auto_20201027_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celula',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JovensDaCelula', to='igreja.lideres'),
        ),
    ]
