# Generated by Django 3.1.1 on 2021-02-28 23:14

from django.db import migrations
import igreja.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0005_auto_20210222_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igreja',
            old_name='image',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='lideres',
            old_name='image',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='celula',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=igreja.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
