# Generated by Django 3.1.1 on 2021-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0006_auto_20210228_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerio', models.CharField(choices=[('Musica', 'Musica'), ('Oracao', 'Oracao'), ('Integracao', 'Integracao'), ('Integracao', 'Integracao')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
            },
        ),
    ]
