# Generated by Django 3.1.1 on 2021-03-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0007_ministerio'),
    ]

    operations = [
        migrations.AddField(
            model_name='celula',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igreja.ministerio'),
        ),
    ]
