# Generated by Django 3.1.1 on 2021-03-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0008_celula_ministerio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerio',
            name='ministerio',
            field=models.CharField(choices=[('Musica', 'Musica'), ('Oracao', 'Oracao'), ('Integracao', 'Integracao'), ('Estudo_biblico', 'Estudo_biblico')], max_length=100),
        ),
    ]
