# Generated by Django 3.1.1 on 2021-03-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0009_auto_20210305_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
