# Generated by Django 3.1.1 on 2021-03-10 15:56

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0010_igreja_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celula',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='celulas'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='igreja'),
        ),
        migrations.AlterField(
            model_name='lideres',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='lideres'),
        ),
    ]
