# Generated by Django 3.1.1 on 2021-03-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0011_auto_20210310_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celula',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='celulas'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='igreja'),
        ),
        migrations.AlterField(
            model_name='lideres',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='lideres'),
        ),
    ]
