# Generated by Django 3.1.1 on 2020-12-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0007_auto_20201128_2016'),
        ('membros', '0003_auto_20200918_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jovens',
            old_name='funcao_na_igreja',
            new_name='ministerio',
        ),
        migrations.RemoveField(
            model_name='jovens',
            name='RegistreSeusDados',
        ),
        migrations.RemoveField(
            model_name='jovens',
            name='celula_atual',
        ),
        migrations.RemoveField(
            model_name='novatos',
            name='celular_participante',
        ),
        migrations.RemoveField(
            model_name='novatos',
            name='igreja_participante',
        ),
        migrations.AddField(
            model_name='jovens',
            name='celula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igreja.celula'),
        ),
    ]
