# Generated by Django 3.1.1 on 2020-12-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_auto_20201206_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerio', models.CharField(choices=[('MUSICA', 'Musica'), ('ORACAO', 'Oracao'), ('INTEGRACAO', 'Integracao')], max_length=100)),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
            },
        ),
        migrations.AddField(
            model_name='novatos',
            name='descreva',
            field=models.TextField(default='Novato', help_text='Descreva algo sobre voce'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jovens',
            name='ministerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.ministerio'),
        ),
    ]
